# Generated by Django 6.0.1 on 2026-01-12 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_tracking', '0003_requestlog_city_requestlog_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
